from ROM import ROM_Methods


# Load reduced model generated by main.py
reduced_model_path = "./Export/Models/reduced_model.pkl"
reduced_model = ROM_Methods.load_reduced_model(reduced_model_path)

reduced_data = reduced_model["reduced_data"]
fom_data = reduced_model["fom_data"]
metadata = reduced_model["metadata"]

print("=" * 80)
print("[Online] Loaded reduced model")
print(f"[Online] metadata={metadata}")
print(f"[Online] V shape={reduced_data['V'].shape}")
print("=" * 80)


# Rebuild ROM object only with the data needed online
rom = ROM_Methods(
    fom_sol=None,
    operators=None,
    fom_data=fom_data,
    training_set=None
)

# Choose new online parameter
mu0 = 2.0
mu1 = 2.0

tol = 1.0e-6
max_it = 10

print("\n[Online] Solving POD-Galerkin ROM")
print(f"[Online] mu0={mu0}, mu1={mu1}")

rom_sol = rom.solve_POD_Galerkin(
    reduced_data,
    mu0=mu0,
    mu1=mu1,
    newton_tol=tol,
    max_iterations=max_it
)

print("\n[Online] Completed")
print(f"[Online] converged={rom_sol['converged']}")
print(f"[Online] iterations={rom_sol['iterations']}")
print(f"[Online] relative_increment={rom_sol['relative_increment']:.3e}")
print(f"[Online] coefficients shape={rom_sol['coefficients'].shape}")
print(f"[Online] reconstructed solution shape={rom_sol['u'].shape}")


# Split reconstructed ROM solution
speed_n_dofs = fom_data["speed_n_dofs"]

u_rom = rom_sol["u"]
u_x_rom = u_rom[0:speed_n_dofs]
u_y_rom = u_rom[speed_n_dofs:2 * speed_n_dofs]
p_rom = u_rom[2 * speed_n_dofs:]

print("\n[Online] Solution components")
print(f"u_x_rom shape={u_x_rom.shape}")
print(f"u_y_rom shape={u_y_rom.shape}")
print(f"p_rom shape={p_rom.shape}")